# Generated by Django 2.2.5 on 2019-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
